### PR TITLE
WIP: Improvements v2 (inc mac support)

### PR DESCRIPTION
**Pull request by JoshuaCarter**
See the changelog/commits for details, but the key features are below, and it's worth noting here that a couple of the env vars will allow **mac** users to use this without edits to the primary files, etc.

Key Features:
- Added `DOCKER_CLISCRIPT_PATH` which is used by `dr.sh` to run `task`.
- Added `task` cmd to `dr.sh` which lists available dev/tasks or runs a task if one is supplied.
- Added `fpmreload` cmd to `dr.sh` which runs `kill -USR2 1` on the php container.
- Added `DOCKER_SSH_VOLUME` used by `docker-compose.yml` to mount ssh dir to phpcli container (needed for mac users). This has no effect for linux users.
- Added `DOCKER_EXEC_IDS` used by `dr.sh` to define the executing user (`uid:gid`) (needed for mac users). This has no effect for linux users.

### CODE REVIEW

**Comment by JoshuaCarter** [comment]
@nyeholt Can I get a review please (still testing mac functionality so don't merge yet, but 99% that will work fine).

**Comment by JoshuaCarter** [comment]
@nyeholt I think this is ready for a merge, can you please review the changes and let me know your thoughts?

**Comment by JoshuaCarter** [comment]
@nyeholt testing complete and it's working on mac. Unfortunately I had to chmod the docker-data dir to 777 for it to work on mac. My guess is that the docker-app middle man introduces a 3rd set of perms needed to mount/write dirs/files in the docker-date directory.

Let me know your thoughts, etc.

**Comment by nyeholt** [comment]
Last one - detect /Users as being a Mac user, and only set 777 if the user's running on a mac.

**Comment by owindsor** [comment]
Depending on how far down the rabbit hole you want to go, you can reliably detect the OS from a shell variable;

Linux:
$ echo $OSTYPE
linux-gnu

Mac (10.11.6):
$ echo $OSTYPE
darwin15

**Comment by JoshuaCarter** [comment]
@owindsor Nice one! I'll look into that :)

**Comment by JoshuaCarter** [comment]
@nyeholt This is ready to merge (I've tested on mac).

Non-mac machines will have 775 for the docker-data dir, and mac will have 777.
I've also removed the chmod on the local project as this was being picked up by git which is problematic, though the chown still occurs which should be sufficient for allowing modules to write to themselves, etc.

@owindsor Couldn't use $OSTYPE as it looks to be a bash var. Ended up using `uname -a`.

https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoGiA5s7eS1ZNSzkz4wCRA9o_Pce3dAg4Az75AKCKV2KIpX0jK

**Pull request merged**
