### PR TITLE
Feature tideways

### PR DESCRIPTION
**Pull request by nyeholt**

### CODE REVIEW

**Comment by nglasl** [comment]
@symric going to need your input on this one please.

**Comment by symric** [comment]
Gettting build errors:

```
E: Package 'mysql-client' has no installation candidate
E: Package 'ssmtp' has no installation candidate
```

**Comment by symric** [comment]
I have updated 2 packages:
mariadb-client should be just a dropin replacement

mstmp I'm not too sure - will require more testing

**Comment by nglasl** [comment]
@nyeholt can you please confirm the changes that were needed here?

**Comment by nyeholt** [comment]
Yep, those both look okay to me.

**Pull request merged**
